export const quizCategoryArray = [
  {
    title: "Science",
    desc: "",
    link: "/quizs",
  },
  {
    title: "Computer",
    desc: "",
    link: "/quizs",
  },
  {
    title: "Generics",
    desc: "",
    link: "/quizs",
  },
  {
    title: "Economics",
    desc: "",
    link: "/quizs",
  },
  {
    title: "Sports",
    desc: "",
    link: "/quizs",
  },
];

export const ArrayofQuizes = [
  {
    quizName: "The Art of computer",
    quizDesc: "",
    quizId: 1,
    category: "computer",
    question: [
      {
        Question: "What is the Main Aspects of ratina (1)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Aspects of ratina (2)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Aspects of ratina (3)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Aspects of ratina (4)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Aspects of ratina(5)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Aspects of ratina(6)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Aspects of ratina (7)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Aspects of ratina (8)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Aspects of ratina (9)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Aspects of ratina(10)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
    ],
  },
  {
    quizName: "The art of science",
    quizDesc: "",
    quizId: 2,
    category: "science",
    question: [
      {
        Question: "What is the Main Science (1)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Science (2)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Science (3)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Science (4)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Science(5)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Science(6)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Science (7)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Science (8)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Science (9)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Science(10)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
    ],
  },
  {
    quizName: "The Art of Economics",
    quizDesc: "",
    quizId: 3,
    category: "Economics",
    question: [
      {
        Question: "What is the Main Economics (1)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Economics (2)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Economics (3)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Economics (4)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Economics(5)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Economics(6)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Economics (7)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Economics (8)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Economics (9)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
      {
        Question: "What is the Main Economics(10)",
        A: "Option 1",
        B: "option2",
        C: "option3",
        D: "option4",
        correct: 1,
      },
    ],
  },
];

export const resultData = [
  {
    category: "Reaction",
    score: 80,
    icon: "./assets/images/icon-reaction.svg",
  },
  {
    category: "Memory",
    score: 92,
    icon: "./assets/images/icon-memory.svg",
  },
  {
    category: "Verbal",
    score: 61,
    icon: "./assets/images/icon-verbal.svg",
  },
  {
    category: "Visual",
    score: 72,
    icon: "./assets/images/icon-visual.svg",
  },
];
