export const projects = [
  {
    title: "Science",
    description:
      "since is a conjunction and preposition used to indicate the starting point of a period of time or reason for something",
    link: "/quizs",
  },
  {
    title: "Computer",
    description:
      "Computers are versatile machines capable of performing complex calculations and tasks, essential for various fields like science, engineering, and everyday life",
    link: "/quizs",
  },
  {
    title: "Tech",
    description:
      "Tech, short for technology, refers to the application of scientific knowledge for practical purposes, driving innovation in fields such as information technology",
    link: "/quizs",
  },
  {
    title: "Economics",
    description:
      "Economics is the study of how societies allocate scarce resources to produce goods and services, focusing on the behavior and interactions of economic agents",
    link: "/quizs",
  },
  {
    title: "Sports",
    description:
      "Personality development involves enhancing one's character, behavior, and attitudes through self-improvement and learning.",
    link: "/quizs",
  },
  {
    title: "Personality development",
    description:
      "Personality development involves enhancing one's character, behavior, and attitudes through self-improvement and learning.",
    link: "/quizs",
  },
];

export const ArrayofQuizes = [
  {
    quizName: "The Art of Computer",
    quizdescription:
      "Explore the fundamental aspects of computer science and its applications.",
    quizId: 1,
    category: "computer",
    question: [
      {
        Question: "What is the main function of the CPU?",
        A: "Store data",
        B: "Process data",
        C: "Transmit data",
        D: "Protect data",
        correct: 2,
      },
      {
        Question: "Which of the following is a programming language?",
        A: "HTTP",
        B: "HTML",
        C: "Python",
        D: "FTP",
        correct: 3,
      },
      {
        Question: "What does RAM stand for?",
        A: "Read Access Memory",
        B: "Random Access Memory",
        C: "Run Access Memory",
        D: "Rapid Access Memory",
        correct: 2,
      },
      {
        Question: "What is the primary purpose of an operating system?",
        A: "Manage software",
        B: "Manage hardware",
        C: "Provide a user interface",
        D: "All of the above",
        correct: 4,
      },
      {
        Question: "Which of these is a type of computer network?",
        A: "LAN",
        B: "WAN",
        C: "MAN",
        D: "All of the above",
        correct: 4,
      },
    ],
  },
  {
    quizName: "Discovering Science",
    quizdescription:
      "Dive into the world of science and explore its various branches and phenomena.",
    quizId: 2,
    category: "Science",
    question: [
      {
        Question: "What is the chemical symbol for water?",
        A: "H2O",
        B: "O2",
        C: "CO2",
        D: "NaCl",
        correct: 1,
      },
      {
        Question: "What planet is known as the Red Planet?",
        A: "Earth",
        B: "Mars",
        C: "Jupiter",
        D: "Venus",
        correct: 2,
      },
      {
        Question: "What is the powerhouse of the cell?",
        A: "Nucleus",
        B: "Mitochondria",
        C: "Ribosome",
        D: "Chloroplast",
        correct: 2,
      },
      {
        Question: "What is the speed of light?",
        A: "300,000 km/s",
        B: "150,000 km/s",
        C: "75,000 km/s",
        D: "1,000 km/s",
        correct: 1,
      },
      {
        Question: "Who proposed the theory of relativity?",
        A: "Isaac Newton",
        B: "Albert Einstein",
        C: "Galileo Galilei",
        D: "Nikola Tesla",
        correct: 2,
      },
    ],
  },
  {
    quizName: "Tech Innovations",
    quizdescription:
      "Test your knowledge on the latest and greatest in technology and innovations.",
    quizId: 3,
    category: "Tech",
    question: [
      {
        Question: "What does IoT stand for?",
        A: "Internet of Things",
        B: "Internet of Technology",
        C: "Input/Output Technology",
        D: "Integrated Operational Technology",
        correct: 1,
      },
      {
        Question: "Which company developed the Android operating system?",
        A: "Apple",
        B: "Microsoft",
        C: "Google",
        D: "Amazon",
        correct: 3,
      },
      {
        Question: "What is blockchain primarily used for?",
        A: "Storing photos",
        B: "Securing transactions",
        C: "Streaming videos",
        D: "Gaming",
        correct: 2,
      },
      {
        Question: "What technology is used for cryptocurrency?",
        A: "Blockchain",
        B: "Artificial Intelligence",
        C: "Virtual Reality",
        D: "Augmented Reality",
        correct: 1,
      },
      {
        Question: "What does VR stand for?",
        A: "Virtual Reality",
        B: "Visual Reality",
        C: "Verified Reality",
        D: "Virtual Response",
        correct: 1,
      },
    ],
  },
  {
    quizName: "Path to Self-Improvement",
    quizDesc:
      "Assess your understanding of key concepts in personality development and self-improvement.",
    quizId: 6,
    category: "Personality Development",
    question: [
      {
        Question: "What is emotional intelligence?",
        A: "Ability to be aware of and manage emotions",
        B: "Level of education",
        C: "IQ score",
        D: "Physical strength",
        correct: 1,
      },
      {
        Question: "Which of the following is a key aspect of self-discipline?",
        A: "Procrastination",
        B: "Consistency",
        C: "Excuses",
        D: "Complaining",
        correct: 2,
      },
      {
        Question: "What is the importance of setting goals?",
        A: "To confuse yourself",
        B: "To have a sense of direction and purpose",
        C: "To waste time",
        D: "To avoid challenges",
        correct: 2,
      },
      {
        Question: "Which of these is a trait of a growth mindset?",
        A: "Fear of failure",
        B: "Belief in fixed abilities",
        C: "Desire to learn and improve",
        D: "Avoiding challenges",
        correct: 3,
      },
      {
        Question: "What is the significance of positive thinking?",
        A: "It attracts negative outcomes",
        B: "It boosts mental well-being and success",
        C: "It leads to complacency",
        D: "It has no impact",
        correct: 2,
      },
    ],
  },
  {
    quizName: "Tech Trivia",
    quizDesc:
      "Test your knowledge on the latest in technology and innovations.",
    quizId: 7,
    category: "Tech",
    question: [
      {
        Question: "What does AI stand for?",
        A: "Artificial Intelligence",
        B: "Automated Interface",
        C: "Analog Input",
        D: "Advanced Information",
        correct: 1,
      },
      {
        Question: "Which company developed the Android operating system?",
        A: "Apple",
        B: "Google",
        C: "Microsoft",
        D: "IBM",
        correct: 2,
      },
      {
        Question: "What is blockchain technology primarily used for?",
        A: "Cryptocurrency transactions",
        B: "Virtual reality",
        C: "Social media",
        D: "E-commerce",
        correct: 1,
      },
      {
        Question:
          "Which programming language is known as the backbone of web development?",
        A: "Python",
        B: "JavaScript",
        C: "C++",
        D: "Ruby",
        correct: 2,
      },
      {
        Question: "What does IoT stand for?",
        A: "Internet of Things",
        B: "Internet of Technology",
        C: "Input Output Technology",
        D: "Integrated Operation Technique",
        correct: 1,
      },
    ],
  },
  {
    quizName: "Science Facts",
    quizDesc:
      "Evaluate your understanding of fundamental scientific concepts and discoveries.",
    quizId: 8,
    category: "Science",
    question: [
      {
        Question: "What is the chemical symbol for water?",
        A: "O2",
        B: "H2O",
        C: "CO2",
        D: "H2",
        correct: 2,
      },
      {
        Question: "Who proposed the theory of relativity?",
        A: "Isaac Newton",
        B: "Galileo Galilei",
        C: "Albert Einstein",
        D: "Nikola Tesla",
        correct: 3,
      },
      {
        Question: "What planet is known as the Red Planet?",
        A: "Earth",
        B: "Jupiter",
        C: "Mars",
        D: "Venus",
        correct: 3,
      },
      {
        Question: "What is the powerhouse of the cell?",
        A: "Nucleus",
        B: "Ribosome",
        C: "Mitochondria",
        D: "Golgi apparatus",
        correct: 3,
      },
      {
        Question: "What is the boiling point of water in Celsius?",
        A: "50°C",
        B: "100°C",
        C: "150°C",
        D: "200°C",
        correct: 2,
      },
    ],
  },
  {
    quizName: "Computer Basics",
    quizDesc:
      "Assess your basic understanding of computer science and technology.",
    quizId: 9,
    category: "Computer",
    question: [
      {
        Question: "What does CPU stand for?",
        A: "Central Processing Unit",
        B: "Computer Personal Unit",
        C: "Central Peripheral Unit",
        D: "Computer Processing Unit",
        correct: 1,
      },
      {
        Question: "What is RAM used for?",
        A: "Permanent storage",
        B: "Processing data",
        C: "Temporary storage",
        D: "Displaying graphics",
        correct: 3,
      },
      {
        Question: "What is the main function of an operating system?",
        A: "To manage computer hardware and software resources",
        B: "To provide internet connectivity",
        C: "To create documents",
        D: "To run antivirus software",
        correct: 1,
      },
      {
        Question: "What is an example of a programming language?",
        A: "HTML",
        B: "CSS",
        C: "Java",
        D: "SQL",
        correct: 3,
      },
      {
        Question: "What is the binary code for the decimal number 10?",
        A: "1010",
        B: "1100",
        C: "1001",
        D: "1110",
        correct: 1,
      },
    ],
  },
  {
    quizName: "Path to Self-Improvement",
    quizDesc:
      "Assess your understanding of key concepts in personality development and self-improvement.",
    quizId: 10,
    category: "Personality Development",
    question: [
      {
        Question: "What is emotional intelligence?",
        A: "Ability to be aware of and manage emotions",
        B: "Level of education",
        C: "IQ score",
        D: "Physical strength",
        correct: 1,
      },
      {
        Question: "Which of the following is a key aspect of self-discipline?",
        A: "Procrastination",
        B: "Consistency",
        C: "Excuses",
        D: "Complaining",
        correct: 2,
      },
      {
        Question: "What is the importance of setting goals?",
        A: "To confuse yourself",
        B: "To have a sense of direction and purpose",
        C: "To waste time",
        D: "To avoid challenges",
        correct: 2,
      },
      {
        Question: "Which of these is a trait of a growth mindset?",
        A: "Fear of failure",
        B: "Belief in fixed abilities",
        C: "Desire to learn and improve",
        D: "Avoiding challenges",
        correct: 3,
      },
      {
        Question: "What is the significance of positive thinking?",
        A: "It attracts negative outcomes",
        B: "It boosts mental well-being and success",
        C: "It leads to complacency",
        D: "It has no impact",
        correct: 2,
      },
    ],
  },
  {
    quizName: "Path to Self-Improvement",
    quizDesc:
      "Assess your understanding of key concepts in personality development and self-improvement.",
    quizId: 11,
    category: "Personality Development",
    question: [
      {
        Question: "What is emotional intelligence?",
        A: "Ability to be aware of and manage emotions",
        B: "Level of education",
        C: "IQ score",
        D: "Physical strength",
        correct: 1,
      },
      {
        Question: "Which of the following is a key aspect of self-discipline?",
        A: "Procrastination",
        B: "Consistency",
        C: "Excuses",
        D: "Complaining",
        correct: 2,
      },
      {
        Question: "What is the importance of setting goals?",
        A: "To confuse yourself",
        B: "To have a sense of direction and purpose",
        C: "To waste time",
        D: "To avoid challenges",
        correct: 2,
      },
      {
        Question: "Which of these is a trait of a growth mindset?",
        A: "Fear of failure",
        B: "Belief in fixed abilities",
        C: "Desire to learn and improve",
        D: "Avoiding challenges",
        correct: 3,
      },
      {
        Question: "What is the significance of positive thinking?",
        A: "It attracts negative outcomes",
        B: "It boosts mental well-being and success",
        C: "It leads to complacency",
        D: "It has no impact",
        correct: 2,
      },
    ],
  },
  {
    quizName: "Tech Innovations",
    quizDesc:
      "Challenge your knowledge on recent technological advancements and trends.",
    quizId: 12,
    category: "Tech",
    question: [
      {
        Question:
          "What technology is used to make telephone calls over the Internet possible?",
        A: "VoIP",
        B: "Bluetooth",
        C: "LTE",
        D: "NFC",
        correct: 1,
      },
      {
        Question: "What is the main purpose of a firewall?",
        A: "To clean viruses from a computer",
        B: "To prevent unauthorized access to a network",
        C: "To manage data storage",
        D: "To enhance the sound quality of a computer",
        correct: 2,
      },
      {
        Question:
          "Which company is known for its search engine and also owns YouTube?",
        A: "Microsoft",
        B: "Yahoo",
        C: "Google",
        D: "Amazon",
        correct: 3,
      },
      {
        Question: "What is a primary benefit of using cloud computing?",
        A: "Increased hardware cost",
        B: "Scalability and resource flexibility",
        C: "Increased power consumption",
        D: "Higher software costs",
        correct: 2,
      },
      {
        Question: "Which technology is primarily used in autonomous vehicles?",
        A: "Blockchain",
        B: "Machine Learning",
        C: "Augmented Reality",
        D: "Quantum Computing",
        correct: 2,
      },
    ],
  },
  {
    quizName: "Scientific Discoveries",
    quizDesc:
      "Explore your understanding of significant scientific breakthroughs and phenomena.",
    quizId: 13,
    category: "Science",
    question: [
      {
        Question: "What is the most abundant gas in Earth's atmosphere?",
        A: "Oxygen",
        B: "Nitrogen",
        C: "Carbon Dioxide",
        D: "Hydrogen",
        correct: 2,
      },
      {
        Question: "Who is known as the father of modern physics?",
        A: "Isaac Newton",
        B: "Albert Einstein",
        C: "Galileo Galilei",
        D: "Niels Bohr",
        correct: 1,
      },
      {
        Question: "What is the unit of electrical resistance?",
        A: "Volt",
        B: "Ampere",
        C: "Ohm",
        D: "Watt",
        correct: 3,
      },
      {
        Question: "What process do plants use to convert sunlight into energy?",
        A: "Respiration",
        B: "Photosynthesis",
        C: "Fermentation",
        D: "Oxidation",
        correct: 2,
      },
      {
        Question: "What particle is responsible for the force of gravity?",
        A: "Photon",
        B: "Electron",
        C: "Graviton",
        D: "Proton",
        correct: 3,
      },
    ],
  },
  {
    quizName: "Advanced Computing",
    quizDesc:
      "Test your in-depth knowledge of computer science and advanced technologies.",
    quizId: 14,
    category: "Computer",
    question: [
      {
        Question: "What is the purpose of a database management system (DBMS)?",
        A: "To perform calculations",
        B: "To store and manage data",
        C: "To design websites",
        D: "To edit videos",
        correct: 2,
      },
      {
        Question: "What does the acronym HTTP stand for?",
        A: "HyperText Transfer Protocol",
        B: "High Transfer Text Protocol",
        C: "HyperText Transport Protocol",
        D: "Hyperlink Transfer Text Protocol",
        correct: 1,
      },
      {
        Question: "Which of the following is a version control system?",
        A: "Linux",
        B: "Git",
        C: "Apache",
        D: "MySQL",
        correct: 2,
      },
      {
        Question: "What is the main function of a router?",
        A: "To connect multiple networks and direct network traffic",
        B: "To secure data",
        C: "To store data",
        D: "To program software",
        correct: 1,
      },
      {
        Question:
          "Which programming language is primarily used for data analysis and machine learning?",
        A: "Java",
        B: "C++",
        C: "Python",
        D: "PHP",
        correct: 3,
      },
    ],
  },
  {
    quizName: "Self-Growth Insights",
    quizDesc:
      "Gauge your knowledge on various aspects of personality development and self-growth.",
    quizId: 15,
    category: "Personality Development",
    question: [
      {
        Question: "What is the main benefit of practicing mindfulness?",
        A: "Increased physical strength",
        B: "Enhanced mental clarity and stress reduction",
        C: "Better mathematical skills",
        D: "Improved multitasking",
        correct: 2,
      },
      {
        Question: "Which of the following helps in building resilience?",
        A: "Ignoring problems",
        B: "Developing coping strategies",
        C: "Avoiding social interactions",
        D: "Relying solely on others",
        correct: 2,
      },
      {
        Question: "What is a key characteristic of effective communication?",
        A: "Talking more than listening",
        B: "Active listening",
        C: "Using technical jargon",
        D: "Interrupting frequently",
        correct: 2,
      },
      {
        Question: "Which of these habits can improve time management skills?",
        A: "Procrastination",
        B: "Setting clear priorities",
        C: "Multitasking",
        D: "Leaving tasks unfinished",
        correct: 2,
      },
      {
        Question: "What is a primary goal of personal development?",
        A: "To become rich",
        B: "To achieve a higher level of self-awareness and personal growth",
        C: "To impress others",
        D: "To avoid challenges",
        correct: 2,
      },
    ],
  },
];

export const leaderBoardData = [
  {
    name: "Santosh Kumar",
    coin: 40,
    rank: 4,
  },
  {
    name: "Harsh Raj",
    coin: 40,
    rank: 5,
  },
  {
    name: "Prabhu Kumar",
    coin: 40,
    rank: 6,
  },
  {
    name: "Yeshvant Kumar",
    coin: 40,
    rank: 7,
  },
  {
    name: "Raju Kumar",
    coin: 40,
    rank: 8,
  },
  {
    name: "Krishna Kumar",
    coin: 40,
    rank: 9,
  },
  {
    name: "Yusuf Mirza",
    coin: 40,
    rank: 10,
  },
  {
    name: "Mohit Kumar",
    coin: 40,
    rank: 11,
  },
  {
    name: "Tansh Kumar",
    coin: 40,
    rank: 12,
  },
  {
    name: "Rahul Kumar",
    coin: 40,
    rank: 13,
  },
  {
    name: "Harshit Kumar",
    coin: 40,
    rank: 14,
  },
  {
    name: "Yoshita Jain",
    coin: 40,
    rank: 15,
  },
  {
    name: "Tahsin Jain",
    coin: 40,
    rank: 16,
  },
  {
    name: "Xavier Travis",
    coin: 40,
    rank: 17,
  },
  {
    name: "Xavier Travis",
    coin: 40,
    rank: 18,
  },
  {
    name: "Ava Johnson",
    coin: 40,
    rank: 19,
  },
  {
    name: "Liam Smith",
    coin: 40,
    rank: 20,
  },
  {
    name: "Olivia Brown",
    coin: 40,
    rank: 21,
  },
  {
    name: "Noah Davis",
    coin: 40,
    rank: 22,
  },
  {
    name: "Emma Wilson",
    coin: 40,
    rank: 23,
  },
  {
    name: "William Jones",
    coin: 40,
    rank: 24,
  },
  {
    name: "Sophia Garcia",
    coin: 40,
    rank: 25,
  },
  {
    name: "James Martinez",
    coin: 40,
    rank: 26,
  },
  {
    name: "Isabella Rodriguez",
    coin: 40,
    rank: 27,
  },
  {
    name: "Benjamin Lewis",
    coin: 40,
    rank: 28,
  },
  {
    name: "Mia Walker",
    coin: 40,
    rank: 29,
  },
  {
    name: "Lucas Hall",
    coin: 40,
    rank: 30,
  },
  {
    name: "Charlotte Allen",
    coin: 40,
    rank: 31,
  },
  {
    name: "Henry Young",
    coin: 40,
    rank: 32,
  },
  {
    name: "Amelia Hernandez",
    coin: 40,
    rank: 33,
  },
  {
    name: "Alexander King",
    coin: 40,
    rank: 34,
  },
  {
    name: "Evelyn Wright",
    coin: 40,
    rank: 35,
  },
  {
    name: "Michael Scott",
    coin: 40,
    rank: 36,
  },
  {
    name: "Harper Green",
    coin: 40,
    rank: 37,
  },
  {
    name: "Elijah Adams",
    coin: 40,
    rank: 38,
  },
  {
    name: "Abigail Nelson",
    coin: 40,
    rank: 39,
  },
  {
    name: "Daniel Carter",
    coin: 40,
    rank: 40,
  },
  {
    name: "Sofia Mitchell",
    coin: 40,
    rank: 41,
  },
  {
    name: "Matthew Perez",
    coin: 40,
    rank: 42,
  },
  {
    name: "Ella Roberts",
    coin: 40,
    rank: 43,
  },
  {
    name: "David Turner",
    coin: 40,
    rank: 44,
  },
  {
    name: "Scarlett Phillips",
    coin: 40,
    rank: 45,
  },
  {
    name: "Joseph Campbell",
    coin: 40,
    rank: 46,
  },
  {
    name: "Avery Parker",
    coin: 40,
    rank: 47,
  },
];
