export const quizCategoryArray = [
  {
    title: "Science",
    desc: "",
    link: "/quizs",
  },
  {
    title: "Computer",
    desc: "",
    link: "/quizs",
  },
  {
    title: "Generics",
    desc: "",
    link: "/quizs",
  },
  {
    title: "Economics",
    desc: "",
    link: "/quizs",
  },
  {
    title: "Sports",
    desc: "",
    link: "/quizs",
  },
];

export const ArrayofQuizes = [
  {
    quizName: "The Art of Computer",
    quizDesc:
      "Explore the fundamental aspects of computer science and its applications.",
    quizId: 1,
    category: "computer",
    question: [
      {
        Question: "What is the main function of the CPU?",
        A: "Store data",
        B: "Process data",
        C: "Transmit data",
        D: "Protect data",
        correct: 2,
      },
      {
        Question: "Which of the following is a programming language?",
        A: "HTTP",
        B: "HTML",
        C: "Python",
        D: "FTP",
        correct: 3,
      },
      {
        Question: "What does RAM stand for?",
        A: "Read Access Memory",
        B: "Random Access Memory",
        C: "Run Access Memory",
        D: "Rapid Access Memory",
        correct: 2,
      },
      {
        Question: "What is the primary purpose of an operating system?",
        A: "Manage software",
        B: "Manage hardware",
        C: "Provide a user interface",
        D: "All of the above",
        correct: 4,
      },
      {
        Question: "Which of these is a type of computer network?",
        A: "LAN",
        B: "WAN",
        C: "MAN",
        D: "All of the above",
        correct: 4,
      },
    ],
  },
  {
    quizName: "Discovering Science",
    quizDesc:
      "Dive into the world of science and explore its various branches and phenomena.",
    quizId: 2,
    category: "science",
    question: [
      {
        Question: "What is the chemical symbol for water?",
        A: "H2O",
        B: "O2",
        C: "CO2",
        D: "NaCl",
        correct: 1,
      },
      {
        Question: "What planet is known as the Red Planet?",
        A: "Earth",
        B: "Mars",
        C: "Jupiter",
        D: "Venus",
        correct: 2,
      },
      {
        Question: "What is the powerhouse of the cell?",
        A: "Nucleus",
        B: "Mitochondria",
        C: "Ribosome",
        D: "Chloroplast",
        correct: 2,
      },
      {
        Question: "What is the speed of light?",
        A: "300,000 km/s",
        B: "150,000 km/s",
        C: "75,000 km/s",
        D: "1,000 km/s",
        correct: 1,
      },
      {
        Question: "Who proposed the theory of relativity?",
        A: "Isaac Newton",
        B: "Albert Einstein",
        C: "Galileo Galilei",
        D: "Nikola Tesla",
        correct: 2,
      },
    ],
  },
  {
    quizName: "Tech Innovations",
    quizDesc:
      "Test your knowledge on the latest and greatest in technology and innovations.",
    quizId: 3,
    category: "tech",
    question: [
      {
        Question: "What does IoT stand for?",
        A: "Internet of Things",
        B: "Internet of Technology",
        C: "Input/Output Technology",
        D: "Integrated Operational Technology",
        correct: 1,
      },
      {
        Question: "Which company developed the Android operating system?",
        A: "Apple",
        B: "Microsoft",
        C: "Google",
        D: "Amazon",
        correct: 3,
      },
      {
        Question: "What is blockchain primarily used for?",
        A: "Storing photos",
        B: "Securing transactions",
        C: "Streaming videos",
        D: "Gaming",
        correct: 2,
      },
      {
        Question: "What technology is used for cryptocurrency?",
        A: "Blockchain",
        B: "Artificial Intelligence",
        C: "Virtual Reality",
        D: "Augmented Reality",
        correct: 1,
      },
      {
        Question: "What does VR stand for?",
        A: "Virtual Reality",
        B: "Visual Reality",
        C: "Verified Reality",
        D: "Virtual Response",
        correct: 1,
      },
    ],
  },
  {
    quizName: "Path to Self-Improvement",
    quizDesc:
      "Assess your understanding of key concepts in personality development and self-improvement.",
    quizId: 4,
    category: "personality development",
    question: [
      {
        Question: "What is emotional intelligence?",
        A: "Ability to be aware of and manage emotions",
        B: "Level of education",
        C: "IQ score",
        D: "Physical strength",
        correct: 1,
      },
      {
        Question: "Which of the following is a key aspect of self-discipline?",
        A: "Procrastination",
        B: "Consistency",
        C: "Excuses",
        D: "Complaining",
        correct: 2,
      },
      {
        Question: "What is the importance of setting goals?",
        A: "To confuse yourself",
        B: "To have a sense of direction and purpose",
        C: "To waste time",
        D: "To avoid challenges",
        correct: 2,
      },
      {
        Question: "Which of these is a trait of a growth mindset?",
        A: "Fear of failure",
        B: "Belief in fixed abilities",
        C: "Desire to learn and improve",
        D: "Avoiding challenges",
        correct: 3,
      },
      {
        Question: "What is the significance of positive thinking?",
        A: "It attracts negative outcomes",
        B: "It boosts mental well-being and success",
        C: "It leads to complacency",
        D: "It has no impact",
        correct: 2,
      },
    ],
  },
];
